<?php

use Illuminate\Database\Seeder;
use App\Model\Information;

class InformationTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $informationData = [
            [
                'id' => '1',
                'about_us' => '<h2>Our Story</h2> <br/> <p>eduCare.com began in 2005. After years in the web hosting industry, we realized that it was near impossible for the average Jane or Joe to create their own website. Traditional web hosting services were simply too complicated, time consuming, and expensive to manage.</p> <p>We created the Website.com Site Builder with the user\'s perspective in mind. We wanted to offer a platform that would require no coding skills or design experience. We keep it simple, so users can focus on creating an amazing website that reflects their brand. Best of all - it\'s free. You can get online, showcase your brand, or start selling products right away.</p> <p>After seeing an increased need for ecommerce solutions, we developed one of the only fully-featured, free and commission-free online store builders, allowing business owners to launch their online business.</p> <p>Today, we\'re proud to empower individuals and small business owners around the world. Everyone deserves a website, and we\'re excited to see what you create.</p>',

                'privacy_policy' => '<h2>Privacy Policy</h2> <br/> <p>Last updated: June 17, 2020</p> <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p> <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.</p> <h2>Interpretation and Definitions</h2> <h5>Interpretation</h5> <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p> <h2>Collecting and Using Your Personal Data</h2> <h5>Personal Data</h5> <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p> <ul><li>Email address</li> <li>First name and last name</li> <li>Phone number</li> <li>Address, State, Province, ZIP/Postal code, City</li> <li>Usage Data</li></ul> <h5>Usage Data</h5> <p>Usage Data is collected automatically when using the Service.</p> <p>Usage Data may include information such as Your Device\'s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p> <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p> <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>',

                'refund_policy' => '<h2>Refund Policy</h2> <br/> <p>Last updated: June 17, 2020</p> <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p> <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.</p> <h2>Interpretation and Definitions</h2> <h5>Interpretation</h5> <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p> <h2>Collecting and Using Your Personal Data</h2> <h5>Personal Data</h5> <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p> <ul><li>Email address</li> <li>First name and last name</li> <li>Phone number</li> <li>Address, State, Province, ZIP/Postal code, City</li> <li>Usage Data</li></ul> <h5>Usage Data</h5> <p>Usage Data is collected automatically when using the Service.</p> <p>Usage Data may include information such as Your Device\'s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p> <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p> <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>',

                'terms_and_condition' => '<h2>Terms & Condition</h2> <br/> <p>Last updated: June 17, 2020</p> <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p> <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.</p> <h2>Interpretation and Definitions</h2> <h5>Interpretation</h5> <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p> <h2>Collecting and Using Your Personal Data</h2> <h5>Personal Data</h5> <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p> <ul><li>Email address</li> <li>First name and last name</li> <li>Phone number</li> <li>Address, State, Province, ZIP/Postal code, City</li> <li>Usage Data</li></ul> <h5>Usage Data</h5> <p>Usage Data is collected automatically when using the Service.</p> <p>Usage Data may include information such as Your Device\'s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p> <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p> <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>'
            ]
        ];

        Information::insert($informationData);
    }
}
